# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb6c5bcadbe072591f3487338ed234d3410fbd2f5cbb2df692c67e4abf1313d1d1e274ef473b2c14dbe7c225c4294ba1bc9dcb7a40812c86fd2304f3a4eb2ed7

test:
  secret_key_base: 7bf54f526a29486e6d42fa65ee4886e14722772e35f42c96faed9d432e2b7c2a6d8813dff9c86055cf4e86cc8fc1486c5fba448b727b7b9b0aa56fa55b735889

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
